/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tresenrayas;

import java.awt.Color;
import javax.swing.JButton;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrea Ortiz
 */
public class VsMaquina extends javax.swing.JFrame {

    int turno = 1;
    JButton btnLista[] = new JButton[9];
    boolean hayGanador = false;

    /**
     * Creates new form VsMaquina
     */
    public VsMaquina() {
        initComponents();
        btnLista[0] = (JButton) add(jButton1);
        btnLista[1] = (JButton) add(jButton2);
        btnLista[2] = (JButton) add(jButton3);
        btnLista[3] = (JButton) add(jButton4);
        btnLista[4] = (JButton) add(jButton5);
        btnLista[5] = (JButton) add(jButton6);
        btnLista[6] = (JButton) add(jButton7);
        btnLista[7] = (JButton) add(jButton8);
        btnLista[8] = (JButton) add(jButton9);
        juegaMaquina();
        desbloquearBtns();
        pintarBtns();
        colorLetraBtns();
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void terminaJuego() {
        quienGano(jButton1, jButton2, jButton3);
        quienGano(jButton4, jButton5, jButton6);
        quienGano(jButton7, jButton8, jButton9);

        quienGano(jButton1, jButton4, jButton7);
        quienGano(jButton2, jButton5, jButton8);
        quienGano(jButton3, jButton6, jButton9);

        quienGano(jButton1, jButton5, jButton9);
        quienGano(jButton3, jButton5, jButton7);
        
        if (!hayGanador && esEmpate()) {
            JOptionPane.showMessageDialog(null, "ES UN EMPATE");
            bloquearBtns();
        }
        
        
    }

    public void quienGano(JButton btn1, JButton btn2, JButton btn3) {
        if (btn1.getText().equals("X") && btn2.getText().equals("X") && btn3.getText().equals("X")) {
            pintaGanador(btn1, btn2, btn3);
            JOptionPane.showMessageDialog(null, "MAS SUERTE PARA LA PROXIMA");
            bloquearBtns();
            hayGanador = true;

        } else if (btn1.getText().equals("O") && btn2.getText().equals("O") && btn3.getText().equals("O")) {
            pintaGanador(btn1, btn2, btn3);
            JOptionPane.showMessageDialog(null, "FELICIDADES GANASTE");
            bloquearBtns();
            hayGanador = true;
        }
    }

    public void analisisMaquina(JButton btn1, JButton btn2, JButton btn3) {
        if ((btn1.getText().equals("O") && btn2.getText().equals("O") && btn3.getText().equals("")) || (btn1.getText().equals("X") && btn2.getText().equals("X") && btn3.getText().equals(""))) {
            btn3.setText("X");
            turno = 2;
        } else if (btn1.getText().equals("O") && btn2.getText().equals("") && btn3.getText().equals("O") || (btn1.getText().equals("X") && btn2.getText().equals("") && btn3.getText().equals("X"))) {
            btn2.setText("X");
            turno = 2;
        } else if (btn1.getText().equals("") && btn2.getText().equals("O") && btn3.getText().equals("O") || (btn1.getText().equals("") && btn2.getText().equals("X") && btn3.getText().equals("X"))) {
            btn1.setText("X");
            turno = 2;
        }
    }

    public void juegaMaquina() {
        if (turno == 1) {
            analisisMaquina(jButton1, jButton2, jButton3);
        }
        if (turno == 1) {
            analisisMaquina(jButton4, jButton5, jButton6);
        }
        if (turno == 1) {
            analisisMaquina(jButton7, jButton8, jButton9);
        }
        if (turno == 1) {
            analisisMaquina(jButton1, jButton4, jButton7);
        }
        if (turno == 1) {
            analisisMaquina(jButton2, jButton5, jButton8);
        }
        if (turno == 1) {
            analisisMaquina(jButton3, jButton6, jButton9);
        }
        if (turno == 1) {
            analisisMaquina(jButton1, jButton5, jButton9);
        }
        if (turno == 1) {
            analisisMaquina(jButton3, jButton5, jButton7);
        }
        if (turno == 1) {
            Random nRamdomico = new Random();
            int aleatorio;
            boolean disponible = true;

            do {

                aleatorio = (int) (nRamdomico.nextDouble() * 9 + 1);

                if (btnLista[aleatorio - 1].getText().equals("")) {
                    btnLista[aleatorio - 1].setText("X");
                    disponible = false;
                }
                System.out.println(aleatorio);

            } while (disponible);
        }
        terminaJuego();
    }
    
    
    public void pintaGanador(JButton btn1, JButton btn2, JButton btn3){
        btn1.setBackground(new Color(229,229,229));
        btn2.setBackground(new Color(229,229,229));
        btn3.setBackground(new Color(229,229,229));
        
        btn1.setForeground(Color.BLACK);
        btn2.setForeground(Color.BLACK);
        btn3.setForeground(Color.BLACK);
        
        
    }

    public void limpieza() {
        for (JButton jButton : btnLista) {
            jButton.setText("");
        }
    }

    public void bloquearBtns() {
        for (JButton jButton : btnLista) {
            jButton.setEnabled(false);
        }
    }

    public void desbloquearBtns() {
        for (JButton jButton : btnLista) {
            jButton.setEnabled(true);
        }
    }
    
    public void pintarBtns() {
        for (JButton jButton : btnLista) {
            jButton.setBackground(Color.BLACK);
        }
    }
    
        
    public void colorLetraBtns() {
        for (JButton jButton : btnLista) {
            jButton.setForeground(new Color(229,229,229));
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(252, 163, 17));
        jButton10.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(20, 33, 61));
        jButton10.setText("REINICIAR JUEGO");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (jButton7.getText().isEmpty()) {
            jButton7.setText("O");
            turno = 1;
        }
        juegaMaquina();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (jButton6.getText().isEmpty()) {
            jButton6.setText("O");
            turno = 1;
        }
        juegaMaquina();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (jButton5.getText().isEmpty()) {
            jButton5.setText("O");
            turno = 1;
        }
        juegaMaquina();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jButton4.getText().isEmpty()) {
            jButton4.setText("O");
            turno = 1;
        }
        juegaMaquina();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (jButton8.getText().isEmpty()) {
            jButton8.setText("O");
            turno = 1;
        }
        juegaMaquina();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (jButton9.getText().isEmpty()) {
            jButton9.setText("O");
            turno = 1;
        }
        juegaMaquina();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        limpieza();
        desbloquearBtns();
        pintarBtns();
        colorLetraBtns();
        hayGanador = false;
        turno = 1;
        juegaMaquina();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jButton3.getText().isEmpty()) {
            jButton3.setText("O");
            turno = 1;
        }
        juegaMaquina();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jButton2.getText().isEmpty()) {
            jButton2.setText("O");
            turno = 1;
        }
        juegaMaquina();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jButton1.getText().isEmpty()) {
            jButton1.setText("O");
            turno = 1;
        }
        juegaMaquina();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VsMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VsMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VsMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VsMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VsMaquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables

    public boolean esEmpate() {
        int vacios = 0;
        for (JButton jButton : btnLista) {
            if (jButton.getText().isBlank()) {
                vacios++;
            }
        }
        return vacios == 0;
    }

}
